version: '3.8'

services:
  wsftp:
    image: wlasaas/wsftp-wla:latest
    container_name: wsftp
    restart: unless-stopped
    user: "1000:1000"  # Define o usuário wsftp explicitamente
    ports:
      - "8031:8080"     # Porta para o WebAdmin
      - "1222:2022"     # Porta SFTP/SSH
    volumes:
      - ./docker/data:/srv/sftpgo/data
      - ./docker/backups:/srv/sftpgo/backups
      - ./docker/static/favicon.png:/usr/share/sftpgo/static/favicon.png  # Volume para favicon
      - ./docker/static/img:/usr/share/sftpgo/static/img  # Volume para imagens estáticas
      - ./docker/static/locales:/usr/share/sftpgo/static/locales  # Volume para traduções
      - ./docker/config/wsftp.json:/etc/sftpgo/sftpgo.json  # Volume para o arquivo de configuração principal
      - ./docker/db:/var/lib/sftpgo  # Volume para o banco de dados SQLite
    environment:
      - SFTPGO_LOG_FILE_PATH=""  # Logs para stdout
      - SFTPGO_DEFAULT_ADMIN_USERNAME=wlasaas  # Usuário admin padrão
      - SFTPGO_DEFAULT_ADMIN_PASSWORD=wlasaas  # Senha admin padrão
      - SFTPGO_DATA_PROVIDER__NAME=wsftp.db  # Nome do arquivo do banco de dados
      - SFTPGO_DATA_PROVIDER__DRIVER=sqlite  # Driver do banco de dados
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s